services:
  - docker

language: c

matrix:
  include:

  - sudo: required
    dist: trusty
    compiler: clang
    env:
    - DOCKER_VERSION=1.9.1
    - DOCKER_INSTALL_URL="get.docker.com/builds/$(uname -s)/$(uname -m)"

  - sudo: required
    dist: trusty
    compiler: clang
    env:
    - DOCKER_VERSION=1.10.0-dev
    - DOCKER_INSTALL_URL=master.dockerproject.org/linux/amd64

before_install:
  - sudo service docker stop
  - sudo rm $(which -a docker)
  - curl -L https://${DOCKER_INSTALL_URL}/docker-${DOCKER_VERSION} > docker
  - chmod +x docker
  - sudo mv docker /usr/bin
  - sudo service docker start
  - docker version
  - docker info

script:
  - docker build -t zchee/h2o .

notifications:
  email: false
  slack:
    rooms:
      secure: JWoUF3PGuK8n+M1zF39dDYiVhBS+jxQXEDBr4Jm6PnlV9JOiHYC+TyklqFrx7BfigA7VD9xEwxMlN/cui2gRPh7HFEKFjAP2ttrR4XPxGEaaCH17ClOecQMEAHEO+iJJcCyHeZUlu/TrvETTVGq1myGybyqDFNeJ6N669dFVUZZ9IayRR97sqvJ6LkjHG4UTj83zi1a+THp4Q2mt3onRR/Z3gIT999EgV7k08qg6cd5SL3uFja35OvLIhUjLlxyXnB2icDaRWMvcGQdS+7QUkPXefKgh9PADlO38o1Tof5xuRy8/rhqwns0iYtKgVfN7pVI8nrfFOrcahYjwh/IRQE4OY3Ai+HqRdZWOf7/GGkcb+0sKihsMnKaFVz1tuWvZL/86NONHaY9YvVs7Gjdf7YxF8BS6k6gUCYNixS+1GcR8JM6aHjBmg02QSAc0XdLpYrGAYAG93KQ99pqzWNbQ9biP7x5YeXoky252UBywlajyDNYaq6NaJk5aNW29rXiFbbPklUIoaJsDRtInsVmicJsMiFI6C+Mm4IcgqyTjt2L7fKxklx0bIX9KEfu54fBd47R7kwDhofzFKCFNsb23jS6Z2LS5NuqtslYrcrT3EZ3jP6rFhzVQfAqhL4A3/EIgY+sPTahTDgsdQPOXXHXeuuM3Yi0Rdy0DYKA6aPSeB2o=
